version: '3.0'

services:

  # Here we run an instance of the client
  # An image is automatically build if not present
  # We map the server on port 80 of the host
  client:
    build:
      context: ./client
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - default

  # Here we run an instance of the server
  # An image is automatically build if not present
  # We map the server on port 8000 of the host
  server:
    build:
      context: ./server
    restart: unless-stopped
    depends_on: 
      - database
    environment:
      - DB_HOST=database
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SENSOR_API_KEY=${SENSOR_API_KEY}
    ports:
      - "8000:80"
    networks:
      - default

  # For the database we use a ready-to-use image
  # of mariadb (drop-in alternative of mysql)
  # More info @ https://hub.docker.com/_/mariadb
  database:
    image: mariadb:10.9.4
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_USER_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - default

  # Here we use the ready-to-use php-my-admin
  # image served with apache web server.
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    depends_on: 
      - database
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - PMA_HOST=database
    ports:
      - "8080:80"
    networks:
      - default

volumes:
  mariadb-data: